"""
fetch_debt_gdp.py
Fetches General Government Gross Debt (% of GDP) for all countries
from the IMF DataMapper API and writes bond-data.js.

Source indicator: GGXWDG_NGDP (WEO dataset)
API: https://www.imf.org/external/datamapper/api/v1/
"""

import requests
import json
from pathlib import Path

BASE = "https://www.imf.org/external/datamapper/api/v1"
INDICATOR = "GGXWDG_NGDP"
OUT_FILE = Path(__file__).parent / "bond-data.js"


def fetch(url):
    r = requests.get(url, timeout=30)
    r.raise_for_status()
    return r.json()


# ── 1. Country names + ISO2 codes ────────────────────────────────────────────
print("Fetching country list...")
countries_raw = fetch(f"{BASE}/countries")
# { "AF": { "label": "Afghanistan", ... }, ... }
# Keys are ISO2 codes
country_meta = {}  # iso2 → { name, iso2 }
for iso2, info in countries_raw.get("countries", {}).items():
    country_meta[iso2] = {
        "name": info.get("label", iso2),
        "iso2": iso2,
    }
print(f"  {len(country_meta)} countries found")


# ── 2. Debt/GDP data ─────────────────────────────────────────────────────────
print(f"Fetching {INDICATOR}...")
data_raw = fetch(f"{BASE}/{INDICATOR}")
# { "values": { "GGXWDG_NGDP": { "AFG": { "2015": 6.8, "2016": 7.2, ... }, ... } } }
series = data_raw.get("values", {}).get(INDICATOR, {})
print(f"  {len(series)} country series returned")


# ── 3. Build output — take latest available year per country ─────────────────
PREFER_YEAR = 2023   # use this year if available, else nearest earlier year

output = {}
for iso3, yearly in series.items():
    if not yearly:
        continue

    # Filter to numeric values only
    valid = {int(y): v for y, v in yearly.items() if v is not None}
    if not valid:
        continue

    # Pick preferred year or nearest earlier
    if PREFER_YEAR in valid:
        year = PREFER_YEAR
    else:
        earlier = [y for y in valid if y <= PREFER_YEAR]
        if not earlier:
            continue
        year = max(earlier)

    value = round(valid[year], 1)

    # IMF DataMapper uses ISO3 for series keys but ISO2 for country list.
    # We keep ISO3 as the map key (matches GeoJSON) and attach ISO2 for flags.
    output[iso3] = {
        "value": value,
        "year":  year,
    }

print(f"  {len(output)} countries with data for ≤{PREFER_YEAR}")


# ── 4. Attach country names using ISO3→ISO2 where possible ───────────────────
# IMF DataMapper /countries uses ISO2; the debt series uses ISO3.
# We also fetch the ISO3 mapping from the DataMapper.
print("Fetching ISO3 → ISO2 mapping...")
iso3_raw = fetch(f"{BASE}/countries")
# The same endpoint returns an "iso3" field inside each entry (if present)
iso3_to_iso2 = {}
for iso2, info in iso3_raw.get("countries", {}).items():
    iso3 = info.get("iso3")
    if iso3:
        iso3_to_iso2[iso3] = {"name": info.get("label", iso2), "iso2": iso2}

for iso3, row in output.items():
    meta = iso3_to_iso2.get(iso3, {})
    row["name"] = meta.get("name", iso3)
    row["iso2"] = meta.get("iso2", "")


# ── 5. Write bond-data.js ────────────────────────────────────────────────────
lines = [
    f"// Auto-generated by fetch_debt_gdp.py",
    f"// Source: IMF DataMapper · {INDICATOR} · General Government Gross Debt (% of GDP)",
    f"// Reference year: {PREFER_YEAR} (or nearest earlier if unavailable)",
    f"// {len(output)} countries",
    "",
    "const DEBT_GDP = {",
]

items = sorted(output.items())
for i, (iso3, row) in enumerate(items):
    comma = "," if i < len(items) - 1 else ""
    name  = row["name"].replace('"', '\\"')
    iso2  = row["iso2"]
    value = row["value"]
    year  = row["year"]
    lines.append(f'  "{iso3}": {{ name: "{name}", iso2: "{iso2}", value: {value}, year: {year} }}{comma}')

lines.append("};")

OUT_FILE.write_text("\n".join(lines), encoding="utf-8")
print(f"\nWritten: {OUT_FILE}  ({OUT_FILE.stat().st_size / 1024:.1f} KB)")
print("Done.")
