// Source: Dalio/Ray Power Index Appendix, page 6
// All z-scores are standardised; Strength Gauge is 0–1 index; percentages are decimals

const COUNTRY_DATA = {
  "United States": {
    "Strength Gauge (0-1)": 0.89,
    "Power: Education": 2.0,
    "Innovation and Technology": 1.9,
    "Competitiveness": -0.4,
    "Military": 2.1,
    "Trade": 1.3,
    "Economic Output": 1.7,
    "Financial Center": 2.7,
    "Reserve Currency Status³": 1.9,
    "Geology": 1.6,
    "Resource Allocation Efficiency": 2.0,
    "Acts of Nature": -0.2,
    "Infrastructure & Investment": 0.9,
    "Character/Determination/Civility": 1.1,
    "Governance/Rule of Law": 0.7,
    "Future Growth Estimate": 0.014,
    "Working-Age Pop. Growth": 0.002,
    "Growth Per Worker Estimate": 0.012,
    "Productivity (income adjusted)": -0.2,
    "What You Pay vs. What You Get": -0.5,
    "Growth: Education": -0.2,
    "Labor Productivity": -0.2,
    "Working Hard": -1.6,
    "Investing": -0.6,
    "Culture": 0.6,
    "Corruption": -0.7,
    "Bureaucracy": 1.4,
    "Rule of Law": 0.5,
    "Savoring Life vs. Achieving": 0.6,
    "Innovation": 2.1,
    "Self Sufficiency": 0.0,
    "Indebtedness": -1.3,
    "Happiness Index": 1.0,
    "Health Index": 1.3,
    "Economic/Financial Position": -1.6,
    "Debt Burden": -1.9,
    "Expected Growth": -0.6,
    "Internal Order": -1.5,
    "Wealth/Values Gap": -1.8,
    "Internal Conflict¹": -1.1,
    "External Order²": -1.0
  },
  "China": {
    "Strength Gauge (0-1)": 0.8,
    "Power: Education": 1.6,
    "Innovation and Technology": 1.8,
    "Competitiveness": 1.0,
    "Military": 0.9,
    "Trade": 1.7,
    "Economic Output": 1.6,
    "Financial Center": 0.2,
    "Reserve Currency Status³": -0.6,
    "Geology": 0.6,
    "Resource Allocation Efficiency": 0.7,
    "Acts of Nature": 0.0,
    "Infrastructure & Investment": 2.5,
    "Character/Determination/Civility": 1.4,
    "Governance/Rule of Law": -0.4,
    "Future Growth Estimate": 0.04,
    "Working-Age Pop. Growth": -0.004,
    "Growth Per Worker Estimate": 0.043,
    "Productivity (income adjusted)": 2.3,
    "What You Pay vs. What You Get": 1.6,
    "Growth: Education": 1.5,
    "Labor Productivity": 1.2,
    "Working Hard": 0.2,
    "Investing": 1.6,
    "Culture": 1.4,
    "Corruption": 0.9,
    "Bureaucracy": 3.0,
    "Rule of Law": 1.4,
    "Savoring Life vs. Achieving": 0.7,
    "Innovation": 2.0,
    "Self Sufficiency": 0.6,
    "Indebtedness": -0.7,
    "Happiness Index": 1.2,
    "Health Index": 1.3,
    "Economic/Financial Position": 0.1,
    "Debt Burden": -0.2,
    "Expected Growth": 0.3,
    "Internal Order": 0.4,
    "Wealth/Values Gap": 0.4,
    "Internal Conflict¹": 0.4,
    "External Order²": -1.0
  },
  "Eurozone": {
    "Strength Gauge (0-1)": 0.56,
    "Power: Education": 0.5,
    "Innovation and Technology": 0.2,
    "Competitiveness": -0.6,
    "Military": -0.1,
    "Trade": 1.2,
    "Economic Output": 1.0,
    "Financial Center": 0.4,
    "Reserve Currency Status³": 0.2,
    "Geology": -0.8,
    "Resource Allocation Efficiency": -0.8,
    "Acts of Nature": 0.1,
    "Infrastructure & Investment": 0.5,
    "Character/Determination/Civility": -1.0,
    "Governance/Rule of Law": -0.5,
    "Future Growth Estimate": 0.002,
    "Working-Age Pop. Growth": -0.007,
    "Growth Per Worker Estimate": 0.009,
    "Productivity (income adjusted)": -1.2,
    "What You Pay vs. What You Get": -0.8,
    "Growth: Education": -0.9,
    "Labor Productivity": 0.1,
    "Working Hard": -2.0,
    "Investing": -0.6,
    "Culture": -0.6,
    "Corruption": 0.0,
    "Bureaucracy": 0.5,
    "Rule of Law": -0.2,
    "Savoring Life vs. Achieving": -1.6,
    "Innovation": 0.2,
    "Self Sufficiency": -2.8,
    "Indebtedness": -1.1,
    "Happiness Index": 0.9,
    "Health Index": 2.2,
    "Economic/Financial Position": -0.9,
    "Debt Burden": -0.4,
    "Expected Growth": -1.0,
    "Internal Order": 0.2,
    "Wealth/Values Gap": 0.0,
    "Internal Conflict¹": 0.3,
    "External Order²": 0.2
  },
  "Germany": {
    "Strength Gauge (0-1)": 0.38,
    "Power: Education": -0.3,
    "Innovation and Technology": -0.2,
    "Competitiveness": -0.8,
    "Military": -0.7,
    "Trade": 0.5,
    "Economic Output": -0.2,
    "Financial Center": -0.1,
    "Reserve Currency Status³": null,
    "Geology": -0.6,
    "Resource Allocation Efficiency": 0.6,
    "Acts of Nature": 1.2,
    "Infrastructure & Investment": -0.4,
    "Character/Determination/Civility": -0.5,
    "Governance/Rule of Law": 0.7,
    "Future Growth Estimate": -0.005,
    "Working-Age Pop. Growth": -0.011,
    "Growth Per Worker Estimate": 0.006,
    "Productivity (income adjusted)": -1.0,
    "What You Pay vs. What You Get": -1.0,
    "Growth: Education": -0.9,
    "Labor Productivity": 0.1,
    "Working Hard": -2.2,
    "Investing": -0.7,
    "Culture": 0.0,
    "Corruption": 0.6,
    "Bureaucracy": 1.3,
    "Rule of Law": 0.2,
    "Savoring Life vs. Achieving": -1.2,
    "Innovation": 1.5,
    "Self Sufficiency": -2.3,
    "Indebtedness": -1.7,
    "Happiness Index": 0.9,
    "Health Index": 2.1,
    "Economic/Financial Position": -0.3,
    "Debt Burden": 0.8,
    "Expected Growth": -1.3,
    "Internal Order": 0.5,
    "Wealth/Values Gap": 0.5,
    "Internal Conflict¹": 0.5,
    "External Order²": null
  },
  "Japan": {
    "Strength Gauge (0-1)": 0.33,
    "Power: Education": 0.1,
    "Innovation and Technology": 0.0,
    "Competitiveness": 0.0,
    "Military": -0.4,
    "Trade": -0.6,
    "Economic Output": -0.2,
    "Financial Center": -0.1,
    "Reserve Currency Status³": -0.4,
    "Geology": -0.9,
    "Resource Allocation Efficiency": 0.6,
    "Acts of Nature": 1.4,
    "Infrastructure & Investment": -0.1,
    "Character/Determination/Civility": 0.2,
    "Governance/Rule of Law": 0.8,
    "Future Growth Estimate": 0.012,
    "Working-Age Pop. Growth": -0.008,
    "Growth Per Worker Estimate": 0.019,
    "Productivity (income adjusted)": 0.4,
    "What You Pay vs. What You Get": 0.1,
    "Growth: Education": 0.8,
    "Labor Productivity": 0.7,
    "Working Hard": -1.3,
    "Investing": 0.0,
    "Culture": 0.5,
    "Corruption": 1.1,
    "Bureaucracy": 1.6,
    "Rule of Law": 1.2,
    "Savoring Life vs. Achieving": -0.5,
    "Innovation": 1.1,
    "Self Sufficiency": -1.1,
    "Indebtedness": -1.3,
    "Happiness Index": 0.6,
    "Health Index": 2.4,
    "Economic/Financial Position": -0.9,
    "Debt Burden": -0.9,
    "Expected Growth": -0.7,
    "Internal Order": 1.3,
    "Wealth/Values Gap": 0.9,
    "Internal Conflict¹": 1.7,
    "External Order²": 0.3
  },
  "Korea": {
    "Strength Gauge (0-1)": 0.32,
    "Power: Education": 0.2,
    "Innovation and Technology": 0.3,
    "Competitiveness": 0.1,
    "Military": -0.3,
    "Trade": -0.7,
    "Economic Output": -0.9,
    "Financial Center": -0.3,
    "Reserve Currency Status³": -0.7,
    "Geology": -0.8,
    "Resource Allocation Efficiency": -0.1,
    "Acts of Nature": 1.7,
    "Infrastructure & Investment": 0.0,
    "Character/Determination/Civility": 0.9,
    "Governance/Rule of Law": -0.1,
    "Future Growth Estimate": 0.018,
    "Working-Age Pop. Growth": -0.012,
    "Growth Per Worker Estimate": 0.03,
    "Productivity (income adjusted)": 0.9,
    "What You Pay vs. What You Get": 0.2,
    "Growth: Education": 1.1,
    "Labor Productivity": 1.0,
    "Working Hard": -1.3,
    "Investing": -0.1,
    "Culture": 1.3,
    "Corruption": -0.8,
    "Bureaucracy": 1.3,
    "Rule of Law": 0.9,
    "Savoring Life vs. Achieving": 0.3,
    "Innovation": 6.0,
    "Self Sufficiency": -0.2,
    "Indebtedness": -1.0,
    "Happiness Index": -0.2,
    "Health Index": 2.3,
    "Economic/Financial Position": 0.1,
    "Debt Burden": 0.6,
    "Expected Growth": -0.5,
    "Internal Order": null,
    "Wealth/Values Gap": 0.7,
    "Internal Conflict¹": null,
    "External Order²": null
  },
  "India": {
    "Strength Gauge (0-1)": 0.3,
    "Power: Education": -0.8,
    "Innovation and Technology": -1.1,
    "Competitiveness": 2.4,
    "Military": 0.4,
    "Trade": -0.7,
    "Economic Output": 0.1,
    "Financial Center": -0.6,
    "Reserve Currency Status³": -0.7,
    "Geology": 0.2,
    "Resource Allocation Efficiency": 0.2,
    "Acts of Nature": -2.4,
    "Infrastructure & Investment": -0.4,
    "Character/Determination/Civility": 1.4,
    "Governance/Rule of Law": -1.2,
    "Future Growth Estimate": 0.063,
    "Working-Age Pop. Growth": 0.009,
    "Growth Per Worker Estimate": 0.053,
    "Productivity (income adjusted)": 4.5,
    "What You Pay vs. What You Get": 3.5,
    "Growth: Education": 1.6,
    "Labor Productivity": 1.5,
    "Working Hard": 2.2,
    "Investing": 3.6,
    "Culture": 2.0,
    "Corruption": 3.8,
    "Bureaucracy": 3.9,
    "Rule of Law": 1.8,
    "Savoring Life vs. Achieving": 0.9,
    "Innovation": 1.2,
    "Self Sufficiency": 0.4,
    "Indebtedness": 1.0,
    "Happiness Index": -0.5,
    "Health Index": -1.4,
    "Economic/Financial Position": 1.0,
    "Debt Burden": 0.3,
    "Expected Growth": 1.1,
    "Internal Order": null,
    "Wealth/Values Gap": 0.0,
    "Internal Conflict¹": null,
    "External Order²": null
  },
  "United Kingdom": {
    "Strength Gauge (0-1)": 0.29,
    "Power: Education": -0.1,
    "Innovation and Technology": -0.3,
    "Competitiveness": -0.5,
    "Military": -0.1,
    "Trade": -0.5,
    "Economic Output": -0.6,
    "Financial Center": 0.0,
    "Reserve Currency Status³": -0.4,
    "Geology": -0.8,
    "Resource Allocation Efficiency": -0.4,
    "Acts of Nature": 0.4,
    "Infrastructure & Investment": -0.6,
    "Character/Determination/Civility": -0.3,
    "Governance/Rule of Law": 1.0,
    "Future Growth Estimate": 0.013,
    "Working-Age Pop. Growth": 0.004,
    "Growth Per Worker Estimate": 0.009,
    "Productivity (income adjusted)": -0.5,
    "What You Pay vs. What You Get": -0.6,
    "Growth: Education": 0.0,
    "Labor Productivity": 0.1,
    "Working Hard": -1.5,
    "Investing": -0.9,
    "Culture": 0.2,
    "Corruption": 0.6,
    "Bureaucracy": 1.9,
    "Rule of Law": 1.1,
    "Savoring Life vs. Achieving": -1.4,
    "Innovation": 0.7,
    "Self Sufficiency": -1.5,
    "Indebtedness": -1.9,
    "Happiness Index": 1.7,
    "Health Index": 2.3,
    "Economic/Financial Position": -1.6,
    "Debt Burden": -1.9,
    "Expected Growth": -0.7,
    "Internal Order": -0.6,
    "Wealth/Values Gap": -0.1,
    "Internal Conflict¹": -1.1,
    "External Order²": 0.3
  },
  "France": {
    "Strength Gauge (0-1)": 0.27,
    "Power: Education": -0.6,
    "Innovation and Technology": -0.4,
    "Competitiveness": -0.7,
    "Military": -0.2,
    "Trade": -0.5,
    "Economic Output": -0.6,
    "Financial Center": -0.2,
    "Reserve Currency Status³": null,
    "Geology": -0.5,
    "Resource Allocation Efficiency": -1.3,
    "Acts of Nature": -0.1,
    "Infrastructure & Investment": -0.3,
    "Character/Determination/Civility": -1.5,
    "Governance/Rule of Law": 0.4,
    "Future Growth Estimate": 0.009,
    "Working-Age Pop. Growth": -0.001,
    "Growth Per Worker Estimate": 0.01,
    "Productivity (income adjusted)": -1.2,
    "What You Pay vs. What You Get": -0.8,
    "Growth: Education": -1.4,
    "Labor Productivity": -0.2,
    "Working Hard": -1.9,
    "Investing": -0.5,
    "Culture": -0.8,
    "Corruption": 0.1,
    "Bureaucracy": 0.7,
    "Rule of Law": 0.4,
    "Savoring Life vs. Achieving": -2.5,
    "Innovation": 0.0,
    "Self Sufficiency": -3.6,
    "Indebtedness": -1.0,
    "Happiness Index": 1.0,
    "Health Index": 2.2,
    "Economic/Financial Position": -1.1,
    "Debt Burden": -1.0,
    "Expected Growth": -0.8,
    "Internal Order": 0.4,
    "Wealth/Values Gap": 0.8,
    "Internal Conflict¹": 0.0,
    "External Order²": null
  },
  "Russia": {
    "Strength Gauge (0-1)": 0.26,
    "Power: Education": -0.7,
    "Innovation and Technology": -0.7,
    "Competitiveness": 0.9,
    "Military": 0.6,
    "Trade": -1.0,
    "Economic Output": -0.5,
    "Financial Center": -1.3,
    "Reserve Currency Status³": -0.7,
    "Geology": 2.0,
    "Resource Allocation Efficiency": -0.2,
    "Acts of Nature": -0.1,
    "Infrastructure & Investment": -1.2,
    "Character/Determination/Civility": 0.3,
    "Governance/Rule of Law": -2.0,
    "Future Growth Estimate": 0.029,
    "Working-Age Pop. Growth": -0.003,
    "Growth Per Worker Estimate": 0.031,
    "Productivity (income adjusted)": 1.2,
    "What You Pay vs. What You Get": 1.4,
    "Growth: Education": 1.4,
    "Labor Productivity": 1.4,
    "Working Hard": -0.3,
    "Investing": 0.5,
    "Culture": -0.2,
    "Corruption": -0.9,
    "Bureaucracy": 1.8,
    "Rule of Law": -0.3,
    "Savoring Life vs. Achieving": -0.8,
    "Innovation": -0.5,
    "Self Sufficiency": -0.7,
    "Indebtedness": 0.5,
    "Happiness Index": 0.0,
    "Health Index": 0.0,
    "Economic/Financial Position": 0.0,
    "Debt Burden": 0.0,
    "Expected Growth": -0.1,
    "Internal Order": -1.8,
    "Wealth/Values Gap": -2.0,
    "Internal Conflict¹": -1.6,
    "External Order²": -1.2
  },
  "Singapore": {
    "Strength Gauge (0-1)": 0.24,
    "Power: Education": -0.5,
    "Innovation and Technology": -0.5,
    "Competitiveness": 0.1,
    "Military": -1.1,
    "Trade": -0.6,
    "Economic Output": -1.5,
    "Financial Center": -0.3,
    "Reserve Currency Status³": -0.7,
    "Geology": -0.5,
    "Resource Allocation Efficiency": 2.1,
    "Acts of Nature": -0.2,
    "Infrastructure & Investment": -0.2,
    "Character/Determination/Civility": 2.7,
    "Governance/Rule of Law": 2.4,
    "Future Growth Estimate": 0.026,
    "Working-Age Pop. Growth": -0.002,
    "Growth Per Worker Estimate": 0.028,
    "Productivity (income adjusted)": 1.4,
    "What You Pay vs. What You Get": 0.2,
    "Growth: Education": 0.9,
    "Labor Productivity": 1.0,
    "Working Hard": -0.9,
    "Investing": -0.2,
    "Culture": 2.2,
    "Corruption": 0.8,
    "Bureaucracy": 3.0,
    "Rule of Law": 2.4,
    "Savoring Life vs. Achieving": 2.1,
    "Innovation": 2.3,
    "Self Sufficiency": 2.5,
    "Indebtedness": -0.9,
    "Happiness Index": 0.5,
    "Health Index": 2.4,
    "Economic/Financial Position": 0.2,
    "Debt Burden": 0.4,
    "Expected Growth": -0.2,
    "Internal Order": null,
    "Wealth/Values Gap": -2.1,
    "Internal Conflict¹": null,
    "External Order²": null
  },
  "Australia": {
    "Strength Gauge (0-1)": 0.23,
    "Power: Education": -0.3,
    "Innovation and Technology": -0.6,
    "Competitiveness": -0.4,
    "Military": -0.7,
    "Trade": -1.1,
    "Economic Output": -1.3,
    "Financial Center": -0.3,
    "Reserve Currency Status³": -0.6,
    "Geology": 1.9,
    "Resource Allocation Efficiency": -0.4,
    "Acts of Nature": 1.5,
    "Infrastructure & Investment": -0.7,
    "Character/Determination/Civility": 0.2,
    "Governance/Rule of Law": 0.9,
    "Future Growth Estimate": 0.021,
    "Working-Age Pop. Growth": 0.006,
    "Growth Per Worker Estimate": 0.015,
    "Productivity (income adjusted)": -0.6,
    "What You Pay vs. What You Get": -0.5,
    "Growth: Education": -0.3,
    "Labor Productivity": -0.2,
    "Working Hard": -1.6,
    "Investing": -0.5,
    "Culture": -0.2,
    "Corruption": 0.1,
    "Bureaucracy": 0.9,
    "Rule of Law": 0.6,
    "Savoring Life vs. Achieving": -0.7,
    "Innovation": -1.0,
    "Self Sufficiency": -1.2,
    "Indebtedness": 0.0,
    "Happiness Index": 1.3,
    "Health Index": 2.3,
    "Economic/Financial Position": -0.4,
    "Debt Burden": -0.4,
    "Expected Growth": -0.4,
    "Internal Order": null,
    "Wealth/Values Gap": 0.6,
    "Internal Conflict¹": null,
    "External Order²": null
  },
  "Turkey": {
    "Strength Gauge (0-1)": 0.21,
    "Power: Education": -1.8,
    "Innovation and Technology": -0.9,
    "Competitiveness": 1.1,
    "Military": -0.5,
    "Trade": -1.1,
    "Economic Output": -0.7,
    "Financial Center": -1.1,
    "Reserve Currency Status³": -0.7,
    "Geology": -0.6,
    "Resource Allocation Efficiency": -0.4,
    "Acts of Nature": -0.1,
    "Infrastructure & Investment": -0.4,
    "Character/Determination/Civility": -0.1,
    "Governance/Rule of Law": -1.2,
    "Future Growth Estimate": 0.04,
    "Working-Age Pop. Growth": 0.004,
    "Growth Per Worker Estimate": 0.036,
    "Productivity (income adjusted)": 1.7,
    "What You Pay vs. What You Get": 1.7,
    "Growth: Education": 1.1,
    "Labor Productivity": 1.6,
    "Working Hard": -0.6,
    "Investing": 0.9,
    "Culture": 0.1,
    "Corruption": 0.3,
    "Bureaucracy": 1.9,
    "Rule of Law": 0.7,
    "Savoring Life vs. Achieving": -1.0,
    "Innovation": 0.0,
    "Self Sufficiency": -1.4,
    "Indebtedness": -0.3,
    "Happiness Index": -0.1,
    "Health Index": 0.7,
    "Economic/Financial Position": 0.3,
    "Debt Burden": 0.2,
    "Expected Growth": 0.3,
    "Internal Order": null,
    "Wealth/Values Gap": -1.1,
    "Internal Conflict¹": null,
    "External Order²": null
  },
  "Canada": {
    "Strength Gauge (0-1)": 0.21,
    "Power: Education": -0.3,
    "Innovation and Technology": -0.7,
    "Competitiveness": -0.5,
    "Military": -1.0,
    "Trade": -0.8,
    "Economic Output": -1.1,
    "Financial Center": -0.3,
    "Reserve Currency Status³": -0.6,
    "Geology": 0.7,
    "Resource Allocation Efficiency": 0.3,
    "Acts of Nature": 1.3,
    "Infrastructure & Investment": -0.7,
    "Character/Determination/Civility": 0.1,
    "Governance/Rule of Law": 0.6,
    "Future Growth Estimate": 0.012,
    "Working-Age Pop. Growth": 0.003,
    "Growth Per Worker Estimate": 0.009,
    "Productivity (income adjusted)": -0.8,
    "What You Pay vs. What You Get": -0.6,
    "Growth: Education": 0.1,
    "Labor Productivity": 0.2,
    "Working Hard": -1.6,
    "Investing": -0.9,
    "Culture": -0.3,
    "Corruption": 0.2,
    "Bureaucracy": 1.1,
    "Rule of Law": 0.4,
    "Savoring Life vs. Achieving": -0.9,
    "Innovation": -1.4,
    "Self Sufficiency": -1.1,
    "Indebtedness": -0.8,
    "Happiness Index": 1.2,
    "Health Index": 2.2,
    "Economic/Financial Position": -0.6,
    "Debt Burden": -0.3,
    "Expected Growth": -0.7,
    "Internal Order": null,
    "Wealth/Values Gap": 0.5,
    "Internal Conflict¹": null,
    "External Order²": null
  },
  "Switzerland": {
    "Strength Gauge (0-1)": 0.19,
    "Power: Education": -0.5,
    "Innovation and Technology": -0.3,
    "Competitiveness": -1.2,
    "Military": -2.0,
    "Trade": -0.8,
    "Economic Output": -1.4,
    "Financial Center": -0.3,
    "Reserve Currency Status³": -0.7,
    "Geology": -0.4,
    "Resource Allocation Efficiency": -0.4,
    "Acts of Nature": 1.3,
    "Infrastructure & Investment": -0.2,
    "Character/Determination/Civility": 0.3,
    "Governance/Rule of Law": 1.2,
    "Future Growth Estimate": 0.002,
    "Working-Age Pop. Growth": -0.003,
    "Growth Per Worker Estimate": 0.005,
    "Productivity (income adjusted)": -1.2,
    "What You Pay vs. What You Get": -1.6,
    "Growth: Education": -2.1,
    "Labor Productivity": -1.6,
    "Working Hard": -2.0,
    "Investing": -0.8,
    "Culture": 0.7,
    "Corruption": 0.1,
    "Bureaucracy": 0.9,
    "Rule of Law": 0.0,
    "Savoring Life vs. Achieving": -1.3,
    "Innovation": 4.5,
    "Self Sufficiency": -0.2,
    "Indebtedness": -1.0,
    "Happiness Index": 1.3,
    "Health Index": 2.3,
    "Economic/Financial Position": -0.5,
    "Debt Burden": 0.2,
    "Expected Growth": -1.0,
    "Internal Order": null,
    "Wealth/Values Gap": -0.5,
    "Internal Conflict¹": null,
    "External Order²": null
  },
  "Brazil": {
    "Strength Gauge (0-1)": 0.18,
    "Power: Education": -1.3,
    "Innovation and Technology": -1.0,
    "Competitiveness": 0.7,
    "Military": -0.5,
    "Trade": -1.1,
    "Economic Output": -0.7,
    "Financial Center": -0.8,
    "Reserve Currency Status³": -0.7,
    "Geology": 1.9,
    "Resource Allocation Efficiency": -1.4,
    "Acts of Nature": -2.4,
    "Infrastructure & Investment": -1.1,
    "Character/Determination/Civility": -0.9,
    "Governance/Rule of Law": -2.4,
    "Future Growth Estimate": 0.017,
    "Working-Age Pop. Growth": 0.001,
    "Growth Per Worker Estimate": 0.016,
    "Productivity (income adjusted)": 0.5,
    "What You Pay vs. What You Get": 1.1,
    "Growth: Education": 1.3,
    "Labor Productivity": 1.3,
    "Working Hard": -0.8,
    "Investing": 1.0,
    "Culture": -1.2,
    "Corruption": -0.5,
    "Bureaucracy": -1.5,
    "Rule of Law": -0.6,
    "Savoring Life vs. Achieving": -2.2,
    "Innovation": -0.4,
    "Self Sufficiency": -2.2,
    "Indebtedness": -0.2,
    "Happiness Index": 1.1,
    "Health Index": 0.3,
    "Economic/Financial Position": -0.5,
    "Debt Burden": -0.3,
    "Expected Growth": -0.5,
    "Internal Order": null,
    "Wealth/Values Gap": -1.8,
    "Internal Conflict¹": null,
    "External Order²": null
  },
  "Netherlands": {
    "Strength Gauge (0-1)": 0.17,
    "Power: Education": -0.8,
    "Innovation and Technology": -0.4,
    "Competitiveness": -0.8,
    "Military": -1.7,
    "Trade": -0.6,
    "Economic Output": -1.4,
    "Financial Center": -0.4,
    "Reserve Currency Status³": null,
    "Geology": -0.4,
    "Resource Allocation Efficiency": 0.1,
    "Acts of Nature": 0.5,
    "Infrastructure & Investment": -0.4,
    "Character/Determination/Civility": -0.3,
    "Governance/Rule of Law": 1.1,
    "Future Growth Estimate": 0.012,
    "Working-Age Pop. Growth": -0.002,
    "Growth Per Worker Estimate": 0.014,
    "Productivity (income adjusted)": -0.7,
    "What You Pay vs. What You Get": -1.0,
    "Growth: Education": -1.5,
    "Labor Productivity": -0.2,
    "Working Hard": -2.0,
    "Investing": -0.6,
    "Culture": 0.5,
    "Corruption": 0.9,
    "Bureaucracy": 1.1,
    "Rule of Law": 0.2,
    "Savoring Life vs. Achieving": -1.5,
    "Innovation": 3.8,
    "Self Sufficiency": -1.5,
    "Indebtedness": -0.9,
    "Happiness Index": 1.5,
    "Health Index": 2.1,
    "Economic/Financial Position": -0.4,
    "Debt Burden": 0.0,
    "Expected Growth": -0.7,
    "Internal Order": 0.8,
    "Wealth/Values Gap": 0.7,
    "Internal Conflict¹": 0.9,
    "External Order²": null
  },
  "Indonesia": {
    "Strength Gauge (0-1)": 0.17,
    "Power: Education": -1.8,
    "Innovation and Technology": -1.2,
    "Competitiveness": 1.6,
    "Military": -0.6,
    "Trade": -1.2,
    "Economic Output": -0.8,
    "Financial Center": -1.0,
    "Reserve Currency Status³": -0.7,
    "Geology": 0.4,
    "Resource Allocation Efficiency": 0.5,
    "Acts of Nature": -2.2,
    "Infrastructure & Investment": -0.5,
    "Character/Determination/Civility": 1.4,
    "Governance/Rule of Law": -1.4,
    "Future Growth Estimate": 0.055,
    "Working-Age Pop. Growth": 0.007,
    "Growth Per Worker Estimate": 0.048,
    "Productivity (income adjusted)": 3.1,
    "What You Pay vs. What You Get": 2.4,
    "Growth: Education": 1.5,
    "Labor Productivity": 1.4,
    "Working Hard": 1.2,
    "Investing": 2.6,
    "Culture": 1.3,
    "Corruption": 1.8,
    "Bureaucracy": 2.5,
    "Rule of Law": 1.1,
    "Savoring Life vs. Achieving": 0.5,
    "Innovation": 1.0,
    "Self Sufficiency": 0.9,
    "Indebtedness": 1.6,
    "Happiness Index": 1.6,
    "Health Index": -0.4,
    "Economic/Financial Position": 1.1,
    "Debt Burden": 0.7,
    "Expected Growth": 0.9,
    "Internal Order": null,
    "Wealth/Values Gap": 0.6,
    "Internal Conflict¹": null,
    "External Order²": null
  },
  "Italy": {
    "Strength Gauge (0-1)": 0.17,
    "Power: Education": -1.0,
    "Innovation and Technology": -0.8,
    "Competitiveness": -0.6,
    "Military": -0.5,
    "Trade": -0.7,
    "Economic Output": -0.8,
    "Financial Center": -0.6,
    "Reserve Currency Status³": null,
    "Geology": -0.7,
    "Resource Allocation Efficiency": -2.2,
    "Acts of Nature": -1.0,
    "Infrastructure & Investment": -0.7,
    "Character/Determination/Civility": -1.4,
    "Governance/Rule of Law": -1.8,
    "Future Growth Estimate": -0.005,
    "Working-Age Pop. Growth": -0.011,
    "Growth Per Worker Estimate": 0.006,
    "Productivity (income adjusted)": -1.8,
    "What You Pay vs. What You Get": -0.7,
    "Growth: Education": -0.3,
    "Labor Productivity": 0.3,
    "Working Hard": -2.0,
    "Investing": -0.5,
    "Culture": -2.2,
    "Corruption": -1.5,
    "Bureaucracy": -1.2,
    "Rule of Law": -2.1,
    "Savoring Life vs. Achieving": -2.0,
    "Innovation": -2.6,
    "Self Sufficiency": -3.8,
    "Indebtedness": -0.8,
    "Happiness Index": 0.8,
    "Health Index": 2.2,
    "Economic/Financial Position": -1.1,
    "Debt Burden": -0.5,
    "Expected Growth": -1.3,
    "Internal Order": null,
    "Wealth/Values Gap": 0.5,
    "Internal Conflict¹": null,
    "External Order²": null
  },
  "Spain": {
    "Strength Gauge (0-1)": 0.17,
    "Power: Education": -0.9,
    "Innovation and Technology": -0.9,
    "Competitiveness": -0.5,
    "Military": -0.8,
    "Trade": -0.9,
    "Economic Output": -1.0,
    "Financial Center": -0.6,
    "Reserve Currency Status³": null,
    "Geology": -0.5,
    "Resource Allocation Efficiency": -1.4,
    "Acts of Nature": -0.7,
    "Infrastructure & Investment": -0.5,
    "Character/Determination/Civility": -1.0,
    "Governance/Rule of Law": -0.7,
    "Future Growth Estimate": 0.003,
    "Working-Age Pop. Growth": -0.007,
    "Growth Per Worker Estimate": 0.01,
    "Productivity (income adjusted)": -1.3,
    "What You Pay vs. What You Get": -0.5,
    "Growth: Education": -0.1,
    "Labor Productivity": 0.5,
    "Working Hard": -1.9,
    "Investing": -0.4,
    "Culture": -1.4,
    "Corruption": -0.8,
    "Bureaucracy": -0.1,
    "Rule of Law": 0.1,
    "Savoring Life vs. Achieving": -1.5,
    "Innovation": -2.8,
    "Self Sufficiency": -3.3,
    "Indebtedness": -0.7,
    "Happiness Index": 0.8,
    "Health Index": 2.3,
    "Economic/Financial Position": -1.1,
    "Debt Burden": -0.9,
    "Expected Growth": -1.0,
    "Internal Order": 0.3,
    "Wealth/Values Gap": 0.6,
    "Internal Conflict¹": -0.1,
    "External Order²": null
  },
  "Saudi Arabia": {
    "Strength Gauge (0-1)": 0.15,
    "Power: Education": -1.2,
    "Innovation and Technology": -1.2,
    "Competitiveness": 0.5,
    "Military": -0.7,
    "Trade": -1.1,
    "Economic Output": -1.2,
    "Financial Center": -0.8,
    "Reserve Currency Status³": -0.7,
    "Geology": 0.3,
    "Resource Allocation Efficiency": 0.2,
    "Acts of Nature": -1.8,
    "Infrastructure & Investment": -0.6,
    "Character/Determination/Civility": 2.3,
    "Governance/Rule of Law": 0.5,
    "Future Growth Estimate": 0.046,
    "Working-Age Pop. Growth": 0.016,
    "Growth Per Worker Estimate": 0.03,
    "Productivity (income adjusted)": 1.2,
    "What You Pay vs. What You Get": 0.8,
    "Growth: Education": 0.7,
    "Labor Productivity": 1.3,
    "Working Hard": 0.0,
    "Investing": 0.3,
    "Culture": 0.7,
    "Corruption": 0.1,
    "Bureaucracy": 2.4,
    "Rule of Law": 1.6,
    "Savoring Life vs. Achieving": 2.0,
    "Innovation": -3.4,
    "Self Sufficiency": 1.6,
    "Indebtedness": 0.8,
    "Happiness Index": 0.5,
    "Health Index": 1.1,
    "Economic/Financial Position": 1.5,
    "Debt Burden": 1.7,
    "Expected Growth": 0.5,
    "Internal Order": null,
    "Wealth/Values Gap": -2.9,
    "Internal Conflict¹": null,
    "External Order²": null
  },
  "Mexico": {
    "Strength Gauge (0-1)": 0.14,
    "Power: Education": -1.5,
    "Innovation and Technology": -1.3,
    "Competitiveness": 0.7,
    "Military": -1.1,
    "Trade": -0.8,
    "Economic Output": -0.8,
    "Financial Center": -1.1,
    "Reserve Currency Status³": -0.7,
    "Geology": -0.3,
    "Resource Allocation Efficiency": -0.4,
    "Acts of Nature": -1.2,
    "Infrastructure & Investment": -1.1,
    "Character/Determination/Civility": 1.6,
    "Governance/Rule of Law": -2.3,
    "Future Growth Estimate": 0.025,
    "Working-Age Pop. Growth": 0.008,
    "Growth Per Worker Estimate": 0.017,
    "Productivity (income adjusted)": 0.8,
    "What You Pay vs. What You Get": 1.1,
    "Growth: Education": 1.3,
    "Labor Productivity": 1.3,
    "Working Hard": 0.4,
    "Investing": 0.0,
    "Culture": -0.5,
    "Corruption": -1.3,
    "Bureaucracy": 0.6,
    "Rule of Law": -0.5,
    "Savoring Life vs. Achieving": 0.4,
    "Innovation": -3.5,
    "Self Sufficiency": 1.2,
    "Indebtedness": 0.3,
    "Happiness Index": 1.4,
    "Health Index": 0.0,
    "Economic/Financial Position": 0.1,
    "Debt Burden": 0.4,
    "Expected Growth": -0.2,
    "Internal Order": null,
    "Wealth/Values Gap": -2.4,
    "Internal Conflict¹": null,
    "External Order²": null
  },
  "South Africa": {
    "Strength Gauge (0-1)": 0.1,
    "Power: Education": -1.7,
    "Innovation and Technology": -1.2,
    "Competitiveness": 0.8,
    "Military": -1.2,
    "Trade": -1.3,
    "Economic Output": -1.2,
    "Financial Center": -0.8,
    "Reserve Currency Status³": -0.7,
    "Geology": -0.2,
    "Resource Allocation Efficiency": -0.6,
    "Acts of Nature": -2.1,
    "Infrastructure & Investment": -1.0,
    "Character/Determination/Civility": -0.5,
    "Governance/Rule of Law": -1.5,
    "Future Growth Estimate": 0.029,
    "Working-Age Pop. Growth": 0.01,
    "Growth Per Worker Estimate": 0.019,
    "Productivity (income adjusted)": 1.1,
    "What You Pay vs. What You Get": 1.3,
    "Growth: Education": null,
    "Labor Productivity": 1.4,
    "Working Hard": -0.7,
    "Investing": 1.4,
    "Culture": -0.3,
    "Corruption": 0.5,
    "Bureaucracy": 1.3,
    "Rule of Law": 1.5,
    "Savoring Life vs. Achieving": -1.5,
    "Innovation": -1.7,
    "Self Sufficiency": -2.0,
    "Indebtedness": 0.4,
    "Happiness Index": 0.1,
    "Health Index": -1.7,
    "Economic/Financial Position": 0.1,
    "Debt Burden": 0.2,
    "Expected Growth": -0.1,
    "Internal Order": null,
    "Wealth/Values Gap": -2.7,
    "Internal Conflict¹": null,
    "External Order²": null
  },
  "Argentina": {
    "Strength Gauge (0-1)": 0.07,
    "Power: Education": -1.8,
    "Innovation and Technology": -1.2,
    "Competitiveness": 0.6,
    "Military": -1.0,
    "Trade": -1.3,
    "Economic Output": -1.2,
    "Financial Center": -1.2,
    "Reserve Currency Status³": -0.7,
    "Geology": -0.3,
    "Resource Allocation Efficiency": -2.2,
    "Acts of Nature": -2.1,
    "Infrastructure & Investment": -1.5,
    "Character/Determination/Civility": -0.2,
    "Governance/Rule of Law": -2.4,
    "Future Growth Estimate": 0.02,
    "Working-Age Pop. Growth": 0.008,
    "Growth Per Worker Estimate": 0.012,
    "Productivity (income adjusted)": 0.4,
    "What You Pay vs. What You Get": 0.9,
    "Growth: Education": 1.2,
    "Labor Productivity": 1.2,
    "Working Hard": 0.1,
    "Investing": 0.0,
    "Culture": -1.0,
    "Corruption": 0.0,
    "Bureaucracy": -0.1,
    "Rule of Law": -0.7,
    "Savoring Life vs. Achieving": -1.7,
    "Innovation": -2.1,
    "Self Sufficiency": -1.2,
    "Indebtedness": -1.0,
    "Happiness Index": 0.9,
    "Health Index": 0.9,
    "Economic/Financial Position": -0.7,
    "Debt Burden": -0.8,
    "Expected Growth": -0.4,
    "Internal Order": null,
    "Wealth/Values Gap": 0.6,
    "Internal Conflict¹": null,
    "External Order²": null
  }
};
const SECTIONS = {"Summary": ["Strength Gauge (0-1)"],
     "Key Eight Measures of Power": ["Education", "Innovation and Technology", "Competitiveness", "Military", "Trade", "Economic Output", "Financial Center", "Reserve Currency Status"],
     "Additional Measures of Power": ["Geology", "Resource Allocation Efficiency", "Acts of Nature", "Infrastructure & Investment", "Character/Determination/Civility", "Governance/Rule of Law"],
     "Future Growth Determinants": ["Future Growth Estimate", "Working-Age Pop. Growth", "Growth Per Worker Estimate"], 
     "Productivity": ["Productivity (income adjusted)", "What You Pay vs. What You Get", "Education", "Labor Productivity", "Working Hard", "Investing", "Culture", "Corruption", "Bureaucracy", "Rule of Law", "Savoring Life vs. Achieving", "Innovation", "Self Sufficiency", "Indebtedness"], 
     "Wellbeing": ["Happiness Index", "Health Index"], 
     "Three Big Cycles": ["Economic/Financial Position", "Debt Burden", "Expected Growth", "Internal Order", "Wealth/Values Gap", "Internal Conflict", "External Order"]};

const UNITS = {"Strength Gauge (0-1)": "index_0_1", "Future Growth Estimate": "percent", "Working-Age Pop. Growth": "percent", "Growth Per Worker Estimate": "percent"};

// Map country names to ISO2 codes for the geo.json
const COUNTRY_TO_ISO2 = {
  "United States": "US", "China": "CN", "Germany": "DE", "Japan": "JP",
  "Korea": "KR", "India": "IN", "United Kingdom": "GB", "France": "FR",
  "Russia": "RU", "Singapore": "SG", "Australia": "AU", "Turkey": "TR",
  "Canada": "CA", "Switzerland": "CH", "Brazil": "BR", "Netherlands": "NL",
  "Indonesia": "ID", "Italy": "IT", "Spain": "ES", "Saudi Arabia": "SA",
  "Mexico": "MX", "South Africa": "ZA", "Argentina": "AR",
  // Eurozone maps to no single country — handled specially
};

// Colorable metrics for the choropleth dropdown
const CHOROPLETH_METRICS = [
  { key: "Strength Gauge (0-1)",        label: "Strength Gauge",                section: "Summary" },
  { key: "Future Growth Estimate",      label: "Future Growth Estimate",        section: "Future Growth" },
  { key: "Education",                   label: "Education",                     section: "Key Eight Measures of Power" },
  { key: "Innovation and Technology",   label: "Innovation & Technology",       section: "Key Eight Measures of Power" },
  { key: "Competitiveness",             label: "Competitiveness",               section: "Key Eight Measures of Power" },
  { key: "Military",                    label: "Military",                      section: "Key Eight Measures of Power" },
  { key: "Trade",                       label: "Trade",                         section: "Key Eight Measures of Power" },
  { key: "Economic Output",             label: "Economic Output",               section: "Key Eight Measures of Power" },
  { key: "Financial Center",            label: "Financial Center",              section: "Key Eight Measures of Power" },
  { key: "Reserve Currency Status",     label: "Reserve Currency Status",       section: "Key Eight Measures of Power" },
  { key: "Economic/Financial Position", label: "Economic/Financial Position",   section: "Cycles" },
  { key: "Internal Order",              label: "Internal Order",                section: "Cycles" },
  { key: "External Order",              label: "External Order",                section: "Cycles" },
];